INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(101, 'BASIC');
INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(102, 'BASIC');
INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(103, 'BASIC');
INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(104, 'BASIC');
INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(105, 'BASIC');

INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(201, 'SUITE');
INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(202, 'SUITE');
INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(203, 'SUITE');
INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(204, 'SUITE');
INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(205, 'SUITE');

INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(301, 'PENTHOUSE');
INSERT INTO ROOM(NUMBER, ROOM_TYPE) VALUES(302, 'PENTHOUSE');